### ISSUE TITLE
-profile options missing

### ISSUE THREAD

**Issue by emayssat-ms** [abutaha/aws-es-proxy#1]
I would like to be able to select the AWS profile to use when starting the proxy.
Currently the profile used is 'default'.
Currently if one uses several profile for same account, the proxy may fails to start with the right credentials.
Like with the awscli, it would be nice to be able to select the profile at the command line.

**Comment by abutaha** [comment]
Hi,

Thanks for mentioning this. I'm working on an update to have this included.

**Comment by markusbecker** [comment]
The documentation is mentioning that roles are support, but there is no input switch for this? Would be great if this could be integrated though?

**Comment by keot** [comment]
_aws-es-proxy_ supports the `AWS_PROFILE` environment variable, so just invoke the proxy with `AWS_PROFILE=profile_name ./aws-es-proxy-0.4-mac-amd64 …`

**Comment by markusbecker** [comment]
Hey keot,

thank you very much. But are you sure that also roles are supported? Pointing to es-test via AWS_PROFILE does give me an error: {"Message":"User: anonymous is not authorized to perform: es:ESHttpGet on resource: xxx-elk"}

[xxx-logon]
aws_access_key_id = xxx
aws_secret_access_key = xxx

[es-test]
role_arn = arn:aws:iam::xxxxx:role/es_test
source_profile = xxx-logon

**Comment by markusbecker** [comment]
Ok, doing the assume role by myself and storing the credentials in $env does work though:

$env:AWS_ACCESS_KEY_ID=$tempcred.Credentials.AccessKeyId
$env:AWS_SECRET_ACCESS_KEY=$tempcred.Credentials.SecretAccessKey
$env:AWS_SESSION_TOKEN=$tempcred.Credentials.SessionToken

**Comment by abutaha** [comment]
It seems no further actions are needed here.

**Comment by AlJohri** [comment]
@abutaha I think this needs to be documented in the README. see #34
