### ISSUE TITLE
Installing Binaries

### ISSUE THREAD

**Issue by rkaplan-sx** [abutaha/aws-es-proxy#10]
Hello,
I'm having trouble installing the executable binaries.  There is no file extension so I'm unsure how to install.  Thanks for your help.

**Comment by jacobleonw** [comment]
hey @rkaplan-sx, on what OS are you using aws-es-proxy?

For example, on macOS 10.12.6, I run it by doing this;
```
$ wget https://github.com/abutaha/aws-es-proxy/releases/download/v0.4/aws-es-proxy-0.4-mac-amd64 -O aws-es-proxy
$ chmod +x aws-es-proxy
$ export AWS_PROFILE=project-a #use if you have more than one set of AWS CLI credentials
$ ./aws-es-proxy -endpoint https://<search-endpoint>.<region>.es.amazonaws.com
```
That will launch the proxy on `127.0.0.1:9200` by default, you can then visit `http://127.0.0.1:9200/_plugin/kibana` in your browser to see the Kibana interface
