### ISSUE TITLE
Missing osd-version, osd-xsrf passthrough in headers

### ISSUE THREAD

**Issue by kgston** [abutaha/aws-es-proxy#115]
Similar to #70, Opensearch requires the same similar headers to be passthrough

**Comment by polak785** [comment]
Thank you a lot @kgston for sharing the patch, it worked perfectly again after I migrate my domain to OpenSearch :)

**Comment by fpSpindola** [comment]
Thanks @kgston 
Worked just fine opening OpenSearch Kibana interface

**Comment by Alien2150** [comment]
Any updates on this? Seems PR is open

**Comment by kgston** [comment]
The project owner seems to have abandoned the project 🤷‍♂️

**Comment by Alien2150** [comment]
So seems Amazon Cognito is the way to go @kgston ? :)

**Comment by kgston** [comment]
I'm not familar with cognito, but I wonder if you can use that without some kind of proxy?

**Comment by Alien2150** [comment]
Yes it's "O-Auth" on AWS

**Comment by kgston** [comment]
Yea, seems like Cognito will provide you a sign in page from which you can then grant access to the dashboard. I've never used it before, but it seems like a valid alternative solution to this proxy. 

As for the nginx proxy, it seems like you need to spin up a separate EC2 instance which then adds additional costs.
