### ISSUE TITLE
proxy shows the source code instead of executing it

### ISSUE THREAD

**Issue by ningliu** [abutaha/aws-es-proxy#12]
When I open the url http://localhost:9200/_plugin/kibana  in Chrome on mac, instead of rendering the page, it shows the source code.
Do you have any idea of why?

[
<img width="500" alt="screen shot 2017-10-12 at 1 56 05 pm" src="https://user-images.githubusercontent.com/2146824/31481279-30b7650a-aee8-11e7-8a67-1fb015a3a4a3.png">
](url)

**Comment by abutaha** [comment]
Hi,

Apologies for the so late response. This looks like javascript is disabled in your browser. The proxy is working, however, your browser is not rendering the output as javascript, but rather as text, and this usually happens when javascript is disabled.

**Comment by abutaha** [comment]
It seems no further actions are needed here.
