### ISSUE TITLE
The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by MrPink** [abutaha/aws-es-proxy#13]
Hi,

I'm getting the following when trying to use the proxy

`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details`

I'm running it with `aws-es-proxy-0.3-linux-amd64 -listen 0.0.0.0:9200 -endpoint https://search-elk-test-s5ksigjmxywxvb33qyhbhejrfy.eu-west-1.es.amazonaws.com`

Any suggestions to what it could be?

Thanks

**Comment by MrPink** [comment]
resolved - works now with the AWS credentials file

**Comment by bossyan** [comment]
How were you able to fix this @MrPink ? What AWS credentials file?
