### ISSUE TITLE
--header "Content-Type: application/json" doesn't works 

### ISSUE THREAD

**Issue by fianny** [abutaha/aws-es-proxy#14]
I am using ES 6.0. 

when I make a request 
curl   --header "Content-Type: application/json"  -XPUT  http://localhost:9200/myindex/   -d'{"settings":{"index.mapping.ignore_malformed": true}}'

It responses
{"error":"Content-Type header is missing","status":406}

Is there a way to pass thru the header? As ES 6.0 mandate the content type header for any RESTful request with json body. 

Thanks!

**Comment by abutaha** [comment]
Hi,

Thanks for reporting this. I'll release a fix soon.

**Comment by abutaha** [comment]
This has been fixed with release of v0.5.

**Comment by fianny** [comment]
Thank you so much for such quick response
