### ISSUE TITLE
SigV4 failing for Kibana Shared Short links (/goto/)

### ISSUE THREAD

**Issue by thomasquatorze** [abutaha/aws-es-proxy#15]
Using aws elasticsearch 5.5.2 hosted service and accessing hosted kibana via aws-es-proxy which works great. Created a Shared Short URL. Accessing short url results in an AWS SigV4 Canonicalization error.

https://kibana.mydomain.com/_plugin/kibana/goto/ce613a4285eeaa035468432fac197ce3

The error points to missing "/app/kibana/" after "/_plugin/kibana/" though adding it to goto link doesn't work either. Not sure if this is a problem with Kibana not generating a useable goto link for aws or with aws-es-proxy 

 The Canonical String for this request should have been\n' GET\n/_plugin/kibana/app/kibana\n\

(partially anonymized error message)
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'GET\n/_plugin/kibana/app/kibana\n\nhost:search-ELIDED.us-west-2.es.amazonaws.com\nx-amz-date:20171208T145130Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c89s6fb92427ae41e4649b934ca495991b7852b855'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20171208T145130Z\n20171208/us-west-2/es/aws4_request\n65dab3f58aa19eab18e4d2c479c3a956sd38a4c0399d35d1c71b9960eba46104'\n"}

**Comment by abutaha** [comment]
Hi,

I'm afraid I didn't understand your use case. Would you please elaborate more?

**Comment by thomasquatorze** [comment]
Hi, When using Kibana and exploring the data by adding filters and queries the url gets very long and convoluted with querystring so sharing the long url can be difficult. Kibana has a Share Short URL feature that Stores the long URL in document in .kibana index and provides a shortened URL (/goto/) to share. Trying to access that short url via aws-es-proxy fails with a SIgV4 issue.

**Comment by abutaha** [comment]
Hi,

Thanks for the clarification. I will check this. 

Q. The user who tries to access the url have aws-es-proxy running on his machine? He will need the proxy to sign the requests too.

**Comment by thomasquatorze** [comment]
All access to kibana goes through a dedicated aws instance running apache in front of aws-es-proxy. All kibana requests go through it and all works great, except when trying access a shortened url link. Thanks

**Comment by abutaha** [comment]
I'm afraid this will not work. /goto/ is modifying the url, which breaks the SigV4 signature.
https://github.com/aws/aws-sdk-go/blob/master/aws/signer/v4/v4.go#L317

**Comment by thomasquatorze** [comment]
I'm sure goo.gl shortener will work but its not as integrated into kibana and I don't think the kibana UI has an option to remove the short link option from being displayed (or replacing it with goo.gl) which can be confusing for users. Thanks for looking into this.
