### ISSUE TITLE
Docker images are automatically build on new tags

### ISSUE THREAD

**Issue by brunsgaard** [abutaha/aws-es-proxy#17]
I can recommend [quay.io](https://quay.io) for this :) Dockerhub is of cause also an option.

Right now I push the image manually to a [repo under my own account](https://quay.io/repository/economic/aws-es-proxy).
It would make more sense if you released it to quay on tags, preferably under an account with the same name as this GitHub account ;)

Thanks for a great project 👍

**Comment by abutaha** [comment]
I'm going to host an image in Dockerhub. I would like to host one in quay.io too, but can't find a free version (unless you can help with that) :)

**Comment by abutaha** [comment]
Official docker image image pushed to https://hub.docker.com/r/abutaha/aws-es-proxy/
