### ISSUE TITLE
uuid.go broke build

### ISSUE THREAD

**Issue by rubelw** [abutaha/aws-es-proxy#18]
Received the following errors because uuid.NewV4() now returns the uuid and and error.  Fixed locally by  u,err := uuid.NewV4() and then converting u to a string.

./aws-es-proxy.go:226:44: multiple-value uuid.NewV4() in single-value context
./aws-es-proxy.go:329:59: multiple-value uuid.NewV4() in single-value context
./aws-es-proxy.go:330:61: multiple-value uuid.NewV4() in single-value context

**Comment by abutaha** [comment]
Thanks for reporting this. Will commit a fix soon.

**Comment by cordoval** [comment]
I am building on quay.io and getting this, so 0.7 is not really feasible
```
# app ./aws-es-proxy.go:226: multiple-value uuid.NewV4() in single-value context ./aws-es-proxy.go:329: multiple-value uuid.NewV4() in single-value context ./aws-es-proxy.go:330: multiple-value uuid.NewV4() in single-value context
```

**Comment by abutaha** [comment]
I uploaded a fix, can you please test?

**Comment by cordoval** [comment]
yes, doing it right now, wait for me for confirmation

**Comment by cordoval** [comment]
building on this https://github.com/cordoval/aws-es-proxy

**Comment by cordoval** [comment]
check here https://quay.io/repository/hospiceworks/aws-es-proxy/build/fa633a1c-fb17-4590-b8a0-7f3d59826a61

**Comment by cordoval** [comment]
<img width="1006" alt="screen shot 2018-01-09 at 4 45 06 pm" src="https://user-images.githubusercontent.com/328359/34744856-9919f396-f55c-11e7-97e3-f277a7980c72.png">

**Comment by cordoval** [comment]
should we close this @abutaha ?

**Comment by cordoval** [comment]
@abutaha confirmed it is working like a charm, can we close this? i will open another ticket for security, the image is very vulnerable like on the tents of vulnerabilities.

**Comment by abutaha** [comment]
Okay, so closing this. Let's keep the talk on the vulnerabilities in #19.
