### ISSUE TITLE
Does not work with ES 6.0

### ISSUE THREAD

**Issue by davideagle** [abutaha/aws-es-proxy#21]
Seems to be creating AWS creds on each request to the proxy when connecting to AWS ES 6.0.1
 ##
2018/01/23 12:34:37 Listening on 0.0.0.0:9200...
2018/01/23 12:34:52 Generated fresh AWS Credentials object
2018/01/23 12:34:53 Generated fresh AWS Credentials object
2018/01/23 12:34:56 Generated fresh AWS Credentials object

**Comment by abutaha** [comment]
Hi, this looks more like an issue within your AWS credential keys. You can use AWSCli to create the credential file.

The below commands will install and configure AWSCli for you:

$ sudo pip install awscli
$ aws configure

**Comment by davideagle** [comment]
I was using env variables as mentioned in the README, shouldn't that work?

export AWS_ACCESS_KEY_ID=AKID1234567890
export AWS_SECRET_ACCESS_KEY=MY-SECRET-KEY

**Comment by abutaha** [comment]
Thanks for the feedback. Will have a look and let you know. Just one more question:

You running the proxy from terminal console or docker?

**Comment by FlorianBruniaux** [comment]
Hello,

Same problem here; 

Does not works on AWS ES 6.2

**Comment by rolodato** [comment]
@abutaha I'm having the same issue, haven't tested with a different version of ES though. I'm passing AWS credentials directly through environment variables, running directly from the Linux 64-bit binary.

**Comment by abutaha** [comment]
@rolodato @FlorianBruniaux @davideagle thanks for reporting this. I can confirm it fails to use the exported variables. Will do a fix and release a new version soon.

**Comment by abutaha** [comment]
@rolodato @FlorianBruniaux @davideagle

I did 2 tests today:

1. Running aws-es-proxy inside docker
2. A brand new EC2 instance (neither awscli and iam role were installed/used)

It worked without any problem.

For some reason I couldn't reproduce the issue, although it happened to me as well. So please try the following:

Docker:

You can try to run it within docker using the below command (don't forget to replace <> with your credentials and ES endpoint)

docker run --rm -it \
   -p 9200:9200 \
   -e AWS_ACCESS_KEY_ID=<> \
   -e AWS_SECRET_ACCESS_KEY=<> \
   abutaha/aws-es-proxy:latest \
   ./aws-es-proxy \
   -verbose \
   -listen 0.0.0.0:9200 \
   -endpoint <>

EC2:

export AWS_ACCESS_KEY_ID=<>
export AWS_SECRET_ACCESS_KEY=<>
go run aws-es-proxy.go -verbose -endpoint <>

Please let me know if you can reproduce the issue.

**Comment by arunjadhav16** [comment]
This is working for me when I setup aws-es-proxy on ec2 instance using role. I can see output for curl command to check status of AWS ES cluster.

 I want to connect AWS ES using private Kibana instance . Kibana is installed on aws EC2 instance along with aws-es-proxy. When I setup Kibana configurations to connect to ES using :  elasticsearch.url: "http://localhost:9200" in kibana.yml.

 I see following errors in Kibana logs
{"type":"log","@timestamp":"2018-08-15T17:02:23Z","tags":["warning","elasticsearch","admin"],"pid":5,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2018-08-15T17:02:23Z","tags":["warning","elasticsearch","admin"],"pid":5,"message":"No living connections"}
{"type":"log","@timestamp":"2018-08-15T17:02:23Z","tags":

Can Private Kibana instance connect to AWS ES using this proxy, if Yes what configurations are needed on Kibana and AWS ES side.

**Comment by discordianfish** [comment]
This is happening to me too on a new cluster with same (or at least very similar) config. When I request something from aws-es-proxy, it returns 200 with empty body and logs a panic:
```
2019/01/31 18:05:21 http: panic serving 10.244.7.2:36794: runtime error: invalid memory address or nil pointer dereference
goroutine 24545 [running]:
net/http.(*conn).serve.func1(0xc42089ab40)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x747160, 0x98fe40)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/abutaha/aws-es-proxy/vendor/github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).Get(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/abutaha/aws-es-proxy/vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:204 +0x6d
github.com/abutaha/aws-es-proxy/vendor/github.com/aws/aws-sdk-go/aws/signer/v4.Signer.signWithBody(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420344500, 0x963760, 0xc4205b25d0, ...)
	/go/src/github.com/abutaha/aws-es-proxy/vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go:337 +0x270
github.com/abutaha/aws-es-proxy/vendor/github.com/aws/aws-sdk-go/aws/signer/v4.Signer.Sign(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420344500, 0x963760, 0xc4205b25d0, ...)
	/go/src/github.com/abutaha/aws-es-proxy/vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go:271 +0xf9
main.(*proxy).ServeHTTP(0xc420164000, 0x965de0, 0xc4209602a0, 0xc42089f400)
	/go/src/github.com/abutaha/aws-es-proxy/aws-es-proxy.go:151 +0x199d
net/http.serverHandler.ServeHTTP(0xc420150d00, 0x965de0, 0xc4209602a0, 0xc42089f400)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42089ab40, 0x966360, 0xc42036b940)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
```
