### ISSUE TITLE
Can not work for China region

### ISSUE THREAD

**Issue by liangruibupt** [abutaha/aws-es-proxy#49]
aws-es-proxy-0.8-linux-amd64 -endpoint https://search-real-time-bushfire-hql7siqa3m4sz6altvkp3t76e4.cn-north-1.es.amazonaws.com.cn

2019/08/14 05:50:24 error: submitted endpoint is not a valid Amazon ElasticSearch Endpoint

The code 
```
if len(parts) == 5 {
			p.region, p.service = parts[1], parts[2]
		} else {
			return fmt.Errorf("error: submitted endpoint is not a valid Amazon ElasticSearch Endpoint")
		}
```
should adopt the China region url

*.cn-north-1.es.amazonaws.com.cn
*.cn-northwest-1.es.amazonaws.com.cn

**Comment by liangruibupt** [comment]
I can quickly workaround by 
```
if (len(parts) == 5 || len(parts) == 6) {
            p.region, p.service = parts[1], parts[2]
        } else {
            return fmt.Errorf("error: submitted endpoint is not a valid Amazon ElasticSearch Endpoint")
        }
```

But I cannot build due to issue #50 

@abutaha can you help on the support China Region?

**Comment by abutaha** [comment]
Hi,

thanks for bringing this on. Will have it updated with a new release I'm preparing.

**Comment by jerry123je** [comment]
Hi,

any update on this issue?

**Comment by abutaha** [comment]
Fixed.
