### ISSUE TITLE
Feature: Docker image needed

### ISSUE THREAD

**Issue by composer22** [abutaha/aws-es-proxy#5]
How about a docker image to wrap things into?

**Comment by abutaha** [comment]
A dockerfile can be done. However, binary files are being provided for Windows, Mac and Linux, so I don't really know if a dockerfile will be of any good.

**Comment by ChrisFernandez** [comment]
@composer22 I am creating a dockerfile on my fork to use internally, but like @abutaha says
unless you need it for AWS or some container solution is really not worth it..
@abutaha I can create a pull request when we have it running fine. But since we run Linux we using it with the linux binary... nothing stops your from building the binary on docker when you create the image with dockerfile.. idk .. let me know ideas I can implement it.

**Comment by em0ney** [comment]
Added a PR with Dockerfile and addition to README. If anyone needs an image to use, check out `gorillastack/aws-es-proxy`

**Comment by abutaha** [comment]
Thanks @em0ney for the PR. I will have it merged in the coming days.

**Comment by inno-ron** [comment]
@em0ney hey, is it possible the Dockerfile overriding the arguments env var with "-h" value, I cannot start the container really, it always outputting the help usage.

**Comment by abutaha** [comment]
Docker file added to the project.

**Comment by cordoval** [comment]
@em0ney thanks project saver 💃

**Comment by cordoval** [comment]
@em0ney i think this repository has to have its own image to be more updated, yours does not even have a link back to here. https://hub.docker.com/r/gorillastack/aws-es-proxy
someone has to do something please 👍

**Comment by brunsgaard** [comment]
related to #17

**Comment by abutaha** [comment]
@cordoval, I'm going to host a docker image in Dockerhub. Will have it released soon.

**Comment by cordoval** [comment]
i think i am having a problem with kibana because of this

but could be something else

<img width="762" alt="screen shot 2018-01-09 at 5 11 24 am" src="https://user-images.githubusercontent.com/328359/34715736-9e2514b2-f4fb-11e7-8c43-c47ff74f3734.png">

**Comment by abutaha** [comment]
I believe this is related to #16. Please try v0.7 (https://github.com/abutaha/aws-es-proxy/releases/). If issue remains, create a new issue to track it.

**Comment by cordoval** [comment]
that is why i needed that build on dockrehub 😊

**Comment by abutaha** [comment]
Official docker imaged pushed to https://hub.docker.com/r/abutaha/aws-es-proxy/
