### ISSUE TITLE
Kibana won't load

### ISSUE THREAD

**Issue by kenhen93** [abutaha/aws-es-proxy#51]
Hello,

I built your aws-es-proxy from source on centos with success. It successfully runs and I can get to the elastic search root that shows the version but when I try to go to Kibana /_plugin/kibana/ I get a blank page. My aws elastic search cluster service is setup in a VPC. My access policy is wide open:

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:us-west-2:xxxxxxxxxxxxx:domain/{cluster_name}/*"
    }
  ]
}

The verbose logs from the aws-es-proxy

2019/08/26 19:43:33 Listening on 127.0.0.1:8080...
2019/08/26 19:46:31 Generated fresh AWS Credentials object

========================
2019/08/26 19:46:31
Remote Address:  127.0.0.1:55130
Request URI:  /
Method:  GET
Status:  200
Took: 0.072s
Body:

========================
2019/08/26 19:46:31
Remote Address:  127.0.0.1:55138
Request URI:  /favicon.ico
Method:  GET
Status:  200
Took: 0.044s
Body:

2019/08/26 19:46:39 Generated fresh AWS Credentials object

========================
2019/08/26 19:46:39
Remote Address:  127.0.0.1:55162
Request URI:  /favicon.ico
Method:  GET
Status:  200
Took: 0.005s
Body:

I would really like to use your application. Please help. Thank you.

**Comment by abutaha** [comment]
What is the cluster version? 6.x?

**Comment by kenhen93** [comment]
I am running 6.5 and 6.7. I would really like to use your proxy if you can address this bug

**Comment by kenhen93** [comment]
@danopia Actually I see what you are saying
