### ISSUE TITLE
301 Error on Kibana Load

### ISSUE THREAD

**Issue by atlowell-smpl** [abutaha/aws-es-proxy#60]
Environment:
-Elasticsearch 2.3 requiring https and restricting access to an IAM user.
-Windows 10 running via the exe

Error:
-On loading http://localhost:9200/_plugin/kibana/, the app crashes stating "301 response missing Location header"
-Cloudwatch logs show 0 http 300 responses and 1 InvalidHostHeaderRequest, which is unlikely to be related because it was 30 minutes ago and I've received this error many times since.  This leads me to believe the issue is with aws-es-proxy mishandling something
-On loading http://localhost:9200/_plugin/kibana/app/kibana there is no crash, but I receive a blank page and a 404 error.

**Comment by abutaha** [comment]
@atlowell-smpl was the proxy working, then it stopped? I will run a test on ES 2.3 on Linux and Windows to check if this is platform related or application.

**Comment by atlowell-smpl** [comment]
@abutaha the proxy was running without displaying error messages prior to the crash, but as for whether it was "working", that is unclear.  As I mentioned above, I was receiving a 404, rather than an access denied, which suggests that perhaps it was able to connect to the server.

**Comment by abutaha** [comment]
This has been fixed in the new code in master branch. I will release a docker image later on with the fix included.
