### ISSUE TITLE
[feat req] allow passing the Elasticsearch endpoint via environment vars

### ISSUE THREAD

**Issue by tedder** [abutaha/aws-es-proxy#71]
Currently it takes some nonstandard leaps to point the proxy to a host in an environment variable. The following is sort of 'pseudocode' for docker config.

doesn't work:
```
environment: ["ES_URL": "http://blah:9200"]
command: ["-endpoint","${ES_URL}"]
```

current workarounds:
```
environment: ["ES_URL": "http://blah:9200"]
command: ["sh", "-c", "aws-es-proxy -endpoint ${ES_URL}"]
command: "aws-es-proxy -endpoint ${ES_URL}"

```

it'd be nice to do:
```
environment: ["ES_URL": "http://blah:9200"]
command: [""]
```
It might be handy for other parameters, but this is the one that tends to vary the most- for instance, in ECS, I can look it up by storing it in `ssm` and then injecting that into `ES_URL` of the `secrets` section.

This is beyond my golang abilities, which is why I'm only putting it as a feature request, not a PR :/

**Comment by saravanan30erd** [comment]
@tedder  Raised the PR for this.
